###########################################################
## Cat                                                   ##
## - - - - - - - - - - - - - - - - - - - - - - - - - - - ##
## Input, Output, Looping                                ##
###########################################################

ever
    # Print prompt
    '' ':' 't' 'u' 'p' 'n' 'i' echo

    # Get input and add a new line
    '\n' inputStr

    # Print the input
    echo
;