###########################################################
## Truth Machine Program                                 ##
## - - - - - - - - - - - - - - - - - - - - - - - - - - - ##
## Looping, Output, Input, Conditionals                  ##
###########################################################


# Prompt the use for a value and convert it to Bool
'' ':' 'e' 'u' 'l' 'a' 'V' echo input

if
    # T -> print 1 for ever
    ever 1 print ;
else
    # F -> print 0 and quit
    0 print
;