###########################################################
## Truth Machine Program                                 ##
## - - - - - - - - - - - - - - - - - - - - - - - - - - - ##
## Looping, Output, Input, Conditionals                  ##
###########################################################


# Prompt the use for a value and convert it to Bool
'' ':' 'e' 'u' 'l' 'a' 'V' echo input

# true  -> print 1 for ever
# false -> print 0 and quit
if
    ever 1 print ;
else
    0 print
;